name: Updating maps cacheKeys

on:
  # schedule:
  #   - cron: "30 * * * *"
  workflow_dispatch:

jobs:
  getRepoCacheVars:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        entry:
          - ALTERNATE_BIOMES
          - APOTHEOSIS
          - APOTHEOSIS_NEW_GAME_PLUS
          - APOTHEOSIS_TUONELA
          - NEW_GAME_PLUS_HD
          - NIGHTMARE_HD
          - NOITAVANIA
          - NOITAVANIA_NEW_GAME_PLUS
          - PURGATORY
          - REGULAR_LEFT_PW
          - REGULAR_MAIN_BRANCH
          - REGULAR_MIDDLE
          - REGULAR_RIGHT_PW

    steps:
      - name: ${{ matrix.entry }}_CACHEKEY
        run: echo "current ${{ matrix.entry }}_CACHEKEY = ${{ vars.${{ matrix.entry }}_CACHEKEY }}"
      
      - name: Get CF deployment for ${{ matrix.entry }}_CACHEKEY
        id: get_cf_deployments_${{ matrix.entry }}
        run: |
          response=$(curl --request GET \
          --header "Authorization: Bearer ${{ secrets.CF_PAGES_READ_ALL_API }}" \
          --header 'Content-Type: application/json' \
          --url "https://api.cloudflare.com/client/v4/accounts/${{ secrets.CF_ACCOUNT_ID }}/pages/projects/${{ vars.${{ matrix.entry }}_CF_PROJECT_NAME }}/deployments")
          echo "response_out: $response"
          echo "=========="
          echo "response_out=$(echo $response| tr '\n' ' ')" >> $GITHUB_OUTPUT
      
      - name: Get modified_on for ${{ matrix.entry }}_CACHEKEY
        id: get_modified_on_${{ matrix.entry }}
        run: |
          modified_on=$(jq -r '.result[0].modified_on' <<< '${{ steps.get_cf_deployments_${{ matrix.entry }}.outputs.response_out }}' | date -u -f - +%s)
          echo "modified_on is $modified_on"
          echo "modified_on=$modified_on" >> $GITHUB_OUTPUT
      
      - name: Github Cachekey Update for ${{ matrix.entry }}_CACHEKEY
        id: gh_cachekey_update_${{ matrix.entry }}
        run: |
          PROJECT_CACHEKEY_VAR="${{ matrix.entry }}_CACHEKEY"
          curl -L \
            -X PATCH \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.GH_NOITAMAP_VARS_ACCESS }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/acidflow-noita/noitamap/actions/variables/${PROJECT_CACHEKEY_VAR}\
            -d "{\"name\":\"${PROJECT_CACHEKEY_VAR}\",\"value\":\"${{ steps.get_modified_on_${{ matrix.entry }}.outputs.modified_on }}\"}"










# # This is a basic workflow that is manually triggered
# name: Bohns tests

# on:
#   # schedule:
#   #   - cron: "30 * * * *"
#   workflow_dispatch:
# jobs:
#   getRepoCacheVars:
#     runs-on: ubuntu-latest
#     steps:
#       - name: regular_middle_cacheKey
#         run: echo "current regular_middle_cacheKey = ${{ vars.regular_middle_cacheKey }}"
#       - name: Get CF deployments
#         id: get_cf_deployments
#         run: |
#           response=$(curl --request GET \
#           --header "Authorization: Bearer ${{ secrets.CF_PAGES_READ_ALL_API }}" \
#           --header 'Content-Type: application/json' \
#           --url "https://api.cloudflare.com/client/v4/accounts/${{ secrets.CF_ACCOUNT_ID }}/pages/projects/${{ vars.REGULAR_MIDDLE_CF_PROJECT_NAME }}/deployments")
#           echo "response_out: $response"
#           echo "=========="
#           echo "response_out=$(echo $response| tr '\n' ' ')" >> $GITHUB_OUTPUT
#       - name: Get modified_on
#         id: get_modified_on
#         run: |
#           modified_on=$(jq -r '.result[0].modified_on' <<< '${{ steps.get_cf_deployments.outputs.response_out }}' | date -u -f - +%s)
#           echo "modified_on is $modified_on"
#           echo "modified_on=$modified_on" >> $GITHUB_OUTPUT
#       - name: Github Cachekey Update for ${{ vars.REGULAR_MIDDLE_CF_PROJECT_NAME }}
#         id: gh_cachekey_update
#         run: |
#           PROJECT_CACHEKEY_VAR="REGULAR_MIDDLE_CACHEKEY"
#           curl -L \
#             -X PATCH \
#             -H "Accept: application/vnd.github+json" \
#             -H "Authorization: Bearer ${{ secrets.GH_NOITAMAP_VARS_ACCESS }}" \
#             -H "X-GitHub-Api-Version: 2022-11-28" \
#             https://api.github.com/repos/acidflow-noita/noitamap/actions/variables/${PROJECT_CACHEKEY_VAR}\
#             -d "{\"name\":\"${PROJECT_CACHEKEY_VAR}\",\"value\":\"${{ steps.get_modified_on.outputs.modified_on }}\"}"


